version: "3.8"

services:
  app:
    image: darthnerda/r-shief-web:latest
    ports:
      - 3000:3000
    command: [ "npm", "start" ]
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf-dev:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

networks:
  app-network:
    driver: bridge
